#!/system/bin/sh
echo 1 > /sys/block/zram0/reset
echo 1036870912 > /sys/block/zram0/disksize
mkswap /dev/block/zram0
swapon /dev/block/zram0
echo "700,1200,20500,20600,20600,25800" > /sys/module/lowmemorykiller/parameters/minfree
echo 100 > /proc/sys/vm/swappiness
#########################
#Techinsider2K-SatySatsZB
#########################
